name: "Workflow D: The Enforcer"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enforce:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # Allow pushing commits
      pull-requests: write     # Allow creating reviews and comments
      issues: write            # Allow creating issue comments
      actions: read            # Allow listing workflow runs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for diff

      - name: Wait for and check other workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          CURRENT_RUN_ID: ${{ github.run_id }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ./.github/scripts/wait-for-workflows.sh
          
      - name: Prepare PR context
        env:
          BASE_REF: ${{ github.base_ref }}
        run: ./.github/scripts/prepare-pr-context.sh

      - name: Audit against Constitution with Gemini CLI
        id: audit
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are the Enforcer for an autonomous development system.
            
            Your task is to review the code changes in this pull request against the repository's CONSTITUTION.md and ensure the intended task has been completed correctly as per TASKS.md.
            
            Please:
            1. Read "CONSTITUTION.md" to understand the repository rules.
            2. Read "TASKS.md" to identify the task(s) this PR is intended to complete.
            3. Read "pr_diff.txt" to examine the changes.
            4. Verify that:
               - The changes comply with ALL rules in CONSTITUTION.md.
               - The intended task(s) from TASKS.md have been implemented correctly and completely.
            5. If there are code violations or the task implementation is incorrect/incomplete, list them as violations.
            6. If everything is compliant and the task is fully satisfied, respond with "COMPLIANT".
            
            Respond in JSON format:
            {
              "compliant": true/false,
              "violations": ["reason/violation 1", "reason/violation 2", ...]
            }
            
      - name: Parse audit result
        id: parse_result
        env:
          AUDIT_RESPONSE: ${{ steps.audit.outputs.summary }}
        run: ./.github/scripts/parse-audit-result.sh
          
      - name: Post violations
        if: steps.parse_result.outputs.compliant == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ./.github/scripts/post-violations.sh
            
      - name: Approve and merge
        if: steps.parse_result.outputs.compliant == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ./.github/scripts/approve-and-merge.sh
