name: "Workflow C: The Troubleshooter"

on:
  workflow_dispatch: # Triggered by Heartbeat workflow

jobs:
  troubleshoot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Fetch blocker question from Jules
        id: fetch_question
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
        run: ./.github/scripts/fetch-question.sh
          
      - name: Generate answer with Gemini CLI
        id: generate_answer
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are the Troubleshooter for an autonomous development system.
            
            Jules has encountered a blocker and needs technical input.
            
            Analyze the codebase and provide a definitive technical answer to the following question:
            
            ${{ env.BLOCKER_QUESTION }}
            
            Please read the following files for context:
            - "CONTEXT_MAP.md"
            - "CONSTITUTION.md"
            
            Provide a clear, actionable answer that Jules can use to proceed.
            
      - name: Save answer
        run: |
          echo "${{ steps.generate_answer.outputs.summary }}" > final_answer.txt
          echo "Answer generated and saved"
          
      - name: Post answer to Jules
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
          SESSION_NAME: ${{ env.SESSION_NAME }}
        run: ./.github/scripts/post-answer.sh
          
      - name: Log troubleshooting
        run: |
          echo "Troubleshooting completed for session ${SESSION_NAME:-unknown}"