steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$_COMMIT_SHA"
      - "."
      - "-f"
      - "Dockerfile"
    id: "Build"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args:
      - "push"
      - "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$_COMMIT_SHA"
    id: "Push"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    dir: "."
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "$_SERVICE_NAME"
      - "--platform=managed"
      - "--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$_COMMIT_SHA"
      - "--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$_COMMIT_SHA,gcb-build-id=$BUILD_ID"
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
      - "--set-env-vars"
      - "GITHUB_REPOSITORY=dllewellyn/autonomous-development-lifecycle,GITHUB_BRANCH=$BRANCH_NAME,NODE_ENV=production"
      - "--update-secrets"
      - "APP_ID=github-app-id:latest,PRIVATE_KEY=github-app-private-key:latest,WEBHOOK_SECRET=github-webhook-secret:latest,GEMINI_API_KEY=gemini-api-key:latest,JULES_API_KEY=jules-api-key:latest,STATE_BUCKET=state-bucket-name:latest"
    id: "Deploy"

images:
  - "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$_COMMIT_SHA"

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: europe-west2-docker.pkg.dev
  _AR_PROJECT_ID: flash-cache-poc
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: europe-west2
  _PLATFORM: managed
  _SERVICE_NAME: autonomous-development-lifecycle
  _REPO_NAME: autonomous-development-lifecycle
  _COMMIT_SHA: latest

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - autonomous-development-lifecycle
